package com.example.forestsys.Classes;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;

@Entity(
        foreignKeys = {@ForeignKey(entity = O_S_ATIVIDADES.class,
                parentColumns = "ID_PROGRAMACAO_ATIVIDADE",
                childColumns =  "ID_PROGRAMACAO_ATIVIDADE",
                onDelete = ForeignKey.NO_ACTION,
                onUpdate = ForeignKey.NO_ACTION)})

public class AVAL_SUBSOLAGEM {
    @ColumnInfo(name = "ID_PROGRAMACAO_ATIVIDADE")
    @PrimaryKey
    private int ID_PROGRAMACAO_ATIVIDADE;

    private double PROFUNDIDADE;
    private double ESTRONDAMENTO_LATERAL_INFERIOR;
    private double ESTRONDAMENTO_LATERAL_SUPERIOR;
    private double FAIXA_SOLO_PREPARADA;
    private double PROFUNDIDADE_ADUBO_INFERIOR;
    private double PROFUNDIDADE_ADUBO_SUPERIOR;
    private double LOCALIZACAO_INSUMO_INFERIOR;
    private double LOCALIZACAO_INSUMO_SUPERIOR;

    public AVAL_SUBSOLAGEM(int ID_PROGRAMACAO_ATIVIDADE, double PROFUNDIDADE, double ESTRONDAMENTO_LATERAL_INFERIOR, double ESTRONDAMENTO_LATERAL_SUPERIOR, double FAIXA_SOLO_PREPARADA, double PROFUNDIDADE_ADUBO_INFERIOR, double PROFUNDIDADE_ADUBO_SUPERIOR, double LOCALIZACAO_INSUMO_INFERIOR, double LOCALIZACAO_INSUMO_SUPERIOR) {
        this.ID_PROGRAMACAO_ATIVIDADE = ID_PROGRAMACAO_ATIVIDADE;
        this.PROFUNDIDADE = PROFUNDIDADE;
        this.ESTRONDAMENTO_LATERAL_INFERIOR = ESTRONDAMENTO_LATERAL_INFERIOR;
        this.ESTRONDAMENTO_LATERAL_SUPERIOR = ESTRONDAMENTO_LATERAL_SUPERIOR;
        this.FAIXA_SOLO_PREPARADA = FAIXA_SOLO_PREPARADA;
        this.PROFUNDIDADE_ADUBO_INFERIOR = PROFUNDIDADE_ADUBO_INFERIOR;
        this.PROFUNDIDADE_ADUBO_SUPERIOR = PROFUNDIDADE_ADUBO_SUPERIOR;
        this.LOCALIZACAO_INSUMO_INFERIOR = LOCALIZACAO_INSUMO_INFERIOR;
        this.LOCALIZACAO_INSUMO_SUPERIOR = LOCALIZACAO_INSUMO_SUPERIOR;
    }

    public int getID_PROGRAMACAO_ATIVIDADE() {
        return ID_PROGRAMACAO_ATIVIDADE;
    }

    public void setID_PROGRAMACAO_ATIVIDADE(int ID_PROGRAMACAO_ATIVIDADE) {
        this.ID_PROGRAMACAO_ATIVIDADE = ID_PROGRAMACAO_ATIVIDADE;
    }

    public double getPROFUNDIDADE() {
        return PROFUNDIDADE;
    }

    public void setPROFUNDIDADE(double PROFUNDIDADE) {
        this.PROFUNDIDADE = PROFUNDIDADE;
    }

    public double getESTRONDAMENTO_LATERAL_INFERIOR() {
        return ESTRONDAMENTO_LATERAL_INFERIOR;
    }

    public void setESTRONDAMENTO_LATERAL_INFERIOR(double ESTRONDAMENTO_LATERAL_INFERIOR) {
        this.ESTRONDAMENTO_LATERAL_INFERIOR = ESTRONDAMENTO_LATERAL_INFERIOR;
    }

    public double getESTRONDAMENTO_LATERAL_SUPERIOR() {
        return ESTRONDAMENTO_LATERAL_SUPERIOR;
    }

    public void setESTRONDAMENTO_LATERAL_SUPERIOR(double ESTRONDAMENTO_LATERAL_SUPERIOR) {
        this.ESTRONDAMENTO_LATERAL_SUPERIOR = ESTRONDAMENTO_LATERAL_SUPERIOR;
    }

    public double getFAIXA_SOLO_PREPARADA() {
        return FAIXA_SOLO_PREPARADA;
    }

    public void setFAIXA_SOLO_PREPARADA(double FAIXA_SOLO_PREPARADA) {
        this.FAIXA_SOLO_PREPARADA = FAIXA_SOLO_PREPARADA;
    }

    public double getPROFUNDIDADE_ADUBO_INFERIOR() {
        return PROFUNDIDADE_ADUBO_INFERIOR;
    }

    public void setPROFUNDIDADE_ADUBO_INFERIOR(double PROFUNDIDADE_ADUBO_INFERIOR) {
        this.PROFUNDIDADE_ADUBO_INFERIOR = PROFUNDIDADE_ADUBO_INFERIOR;
    }

    public double getPROFUNDIDADE_ADUBO_SUPERIOR() {
        return PROFUNDIDADE_ADUBO_SUPERIOR;
    }

    public void setPROFUNDIDADE_ADUBO_SUPERIOR(double PROFUNDIDADE_ADUBO_SUPERIOR) {
        this.PROFUNDIDADE_ADUBO_SUPERIOR = PROFUNDIDADE_ADUBO_SUPERIOR;
    }

    public double getLOCALIZACAO_INSUMO_INFERIOR() {
        return LOCALIZACAO_INSUMO_INFERIOR;
    }

    public void setLOCALIZACAO_INSUMO_INFERIOR(double LOCALIZACAO_INSUMO_INFERIOR) {
        this.LOCALIZACAO_INSUMO_INFERIOR = LOCALIZACAO_INSUMO_INFERIOR;
    }

    public double getLOCALIZACAO_INSUMO_SUPERIOR() {
        return LOCALIZACAO_INSUMO_SUPERIOR;
    }

    public void setLOCALIZACAO_INSUMO_SUPERIOR(double LOCALIZACAO_INSUMO_SUPERIOR) {
        this.LOCALIZACAO_INSUMO_SUPERIOR = LOCALIZACAO_INSUMO_SUPERIOR;
    }
}

